dist: trusty
language: ruby
addons:
  apt:
    sources:
      - sourceline: "ppa:mc3man/trusty-media"
    packages:
      - libglib2.0-dev
      - zlib1g-dev 
      - git 
      - libvips-dev 
      - libvips-tools 
      - ffmpeg 
      - mkvtoolnix
      - postgresql-9.6 
      - postgresql-server-dev-9.6
before_install:
  - git clone https://github.com/r888888888/test_parser.git /tmp/test_parser
  - cd /tmp/test_parser
  - make install

env:
  global:
    - DATABASE_URL="postgresql:///danbooru_test?template=template0"

script:
  - bin/rake"