dist: trusty
language: ruby
services:
  - memcached
addons:
  apt:
    postgresql: "9.6"
    sources:
      - sourceline: "ppa:mc3man/trusty-media"
    packages:
      - build-essential 
      - automake
      - libssl-dev
      - libxml2-dev 
      - libxslt-dev 
      - ncurses-dev
      - libreadline-dev
      - libcurl4-openssl-dev
      - sendmail-bin 
      - sendmail
      - coreutils
      - libglib2.0
      - libglib2.0-dev
      - git 
      - libvips-dev 
      - libvips-tools 
      - ffmpeg 
      - mkvtoolnix
      - postgresql-9.6 
      - postgresql-server-dev-9.6
before_install:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib  
before_script:
  - git clone https://github.com/r888888888/test_parser.git /tmp/test_parser
  - cd /tmp/test_parser
  - make install
  - cd $BUILD_DIR; bin/rake db:create db:migrate

env:
  global:
    - BUILD_DIR="/build"
    - DATABASE_URL="postgresql:///travis_ci_test?template=template0"

script:
  - bin/rake