# This sets up a docker container suitable for use with Travis CI

FROM ruby:2.5.1-slim-stretch

RUN apt-get update
RUN apt-get -y install apt-utils build-essential automake libssl-dev libxml2-dev libxslt-dev ncurses-dev sudo libreadline-dev flex bison ragel memcached libmemcached-dev git curl libcurl4-openssl-dev imagemagick libmagickcore-dev libmagickwand-dev sendmail-bin sendmail postgresql-client libpq-dev nginx ssh coreutils libavcodec-dev mkvtoolnix emacs24-nox telnet libvips42 libvips-tools libvips-dev
RUN useradd -ms /bin/bash danbooru -u 1000
RUN mkdir /app
RUN mkdir -p /var/www/danbooru/shared/data
COPY . /app
RUN chown -R danbooru:danbooru /app
RUN chown -R danbooru:danbooru /var/www/danbooru
RUN mkdir /var/run/danbooru
RUN chown danbooru:danbooru /var/run/danbooru
EXPOSE 3000
USER danbooru
RUN echo 'gem: --no-document' > ~/.gemrc
RUN gem install bundler
WORKDIR /app
RUN bundle install
COPY script/install/database.yml.templ /app/config/database.yml
COPY script/install/danbooru_local_config.rb.templ /app/config/danbooru_local_config.rb