version: '3'
services:
  db:
    image: r888888888/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=73e1ac2e91eb52a9981d09fca561aac3
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    command: memcached
  archives:
    image: r888888888/archives
    command: bash -l -c 'cd /app ; bundle exec rake db:create ; bundle exec rake db:migrate'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=73e1ac2e91eb52a9981d09fca561aac3
      - RAILS_ENV=test
      - AMAZON_KEY
      - AMAZON_SQS_REGION
      - AMAZON_SECRET
      - SQS_ARCHIVES_URL
      - RUN
    depends_on:
      - db
  danbooru:
    environment:
      - SECRET_TOKEN=73e1ac2e91eb52a9981d09fca561aac3
      - SESSION_SECRET_KEY=73e1ac2e91eb52a9981d09fca561aac3
      - DATABASE_URL=postgresql://postgres:73e1ac2e91eb52a9981d09fca561aac3@db:5432
      - RO_DATABASE_URL=postgresql://postgres:73e1ac2e91eb52a9981d09fca561aac3@db:5432
      - ARCHIVE_DATABASE_URL=postgresql://postgres:73e1ac2e91eb52a9981d09fca561aac3@db:5432/db_archive_test
      - DANBOORU_MEMCACHED_SERVERS=memcached:11211
      - RAILS_ENV=test
      - DANBOORU_AWS_SQS_ARCHIVE_URL=something
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: bash -l -c 'cd /app ; bin/rake db:create ; bin/rake db:migrate ; bin/rake db:seed ; bundle exec rake'
    depends_on:
      - db
      - memcached
      - archives
